//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectionStudio.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReflectionStudio.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string CORE_LOADING {
            get {
                return ResourceManager.GetString("CORE_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading  !.
        /// </summary>
        internal static string CORE_LOADING_ERROR {
            get {
                return ResourceManager.GetString("CORE_LOADING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method map build has been interrupted !.
        /// </summary>
        internal static string CORE_MAP_INTERUPT {
            get {
                return ResourceManager.GetString("CORE_MAP_INTERUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the {0} assembly method mapping.
        /// </summary>
        internal static string CORE_MAP_METHOD {
            get {
                return ResourceManager.GetString("CORE_MAP_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the methods map....
        /// </summary>
        internal static string CORE_MAP_START {
            get {
                return ResourceManager.GetString("CORE_MAP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method map has been sucessfully build !.
        /// </summary>
        internal static string CORE_MAP_STOP {
            get {
                return ResourceManager.GetString("CORE_MAP_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly parsing canceled !.
        /// </summary>
        internal static string CORE_PARSING_CANCELED {
            get {
                return ResourceManager.GetString("CORE_PARSING_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly parsing errors !.
        /// </summary>
        internal static string CORE_PARSING_ERROR {
            get {
                return ResourceManager.GetString("CORE_PARSING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly parsing finished !.
        /// </summary>
        internal static string CORE_PARSING_FINISH {
            get {
                return ResourceManager.GetString("CORE_PARSING_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start parsing assemblies in the project....
        /// </summary>
        internal static string CORE_PARSING_START {
            get {
                return ResourceManager.GetString("CORE_PARSING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start profiling the {0} class....
        /// </summary>
        internal static string CORE_PROFILING_CLASS {
            get {
                return ResourceManager.GetString("CORE_PROFILING_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling {0}.
        /// </summary>
        internal static string CORE_PROFILING_METHOD {
            get {
                return ResourceManager.GetString("CORE_PROFILING_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling resume : {0} method(s) profiled. {1} method(s) ignored. Success !.
        /// </summary>
        internal static string CORE_PROFILING_RESUME {
            get {
                return ResourceManager.GetString("CORE_PROFILING_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the profiled assembly {0}...sucessfull !.
        /// </summary>
        internal static string CORE_PROFILING_SAVE {
            get {
                return ResourceManager.GetString("CORE_PROFILING_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling the {0} assembly.
        /// </summary>
        internal static string CORE_PROFILING_START {
            get {
                return ResourceManager.GetString("CORE_PROFILING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been closed !.
        /// </summary>
        internal static string CORE_PROJECT_CLOSED {
            get {
                return ResourceManager.GetString("CORE_PROJECT_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project successfully loaded !.
        /// </summary>
        internal static string CORE_PROJECT_LOADED {
            get {
                return ResourceManager.GetString("CORE_PROJECT_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been saved !.
        /// </summary>
        internal static string CORE_PROJECT_SAVED {
            get {
                return ResourceManager.GetString("CORE_PROJECT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string CORE_SAVING {
            get {
                return ResourceManager.GetString("CORE_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving !.
        /// </summary>
        internal static string CORE_SAVING_ERROR {
            get {
                return ResourceManager.GetString("CORE_SAVING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse the snapshot result....
        /// </summary>
        internal static string CORE_SNAPSHOT_CALCULATE {
            get {
                return ResourceManager.GetString("CORE_SNAPSHOT_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the snapshot map....
        /// </summary>
        internal static string CORE_SNAPSHOT_LOAD_MAP {
            get {
                return ResourceManager.GetString("CORE_SNAPSHOT_LOAD_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot successfully loaded !.
        /// </summary>
        internal static string CORE_SNAPSHOT_LOADED {
            get {
                return ResourceManager.GetString("CORE_SNAPSHOT_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving the snapshot method&apos;s map....
        /// </summary>
        internal static string CORE_SNAPSHOT_RESOLVE_MAP {
            get {
                return ResourceManager.GetString("CORE_SNAPSHOT_RESOLVE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the distant snapshot after retreiving it ?.
        /// </summary>
        internal static string MSG_DELETE_DISTANT_SNAP {
            get {
                return ResourceManager.GetString("MSG_DELETE_DISTANT_SNAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured ! Please, consult the log file for details..
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has some changes! Do you want to save it ?..
        /// </summary>
        internal static string MSG_PRJ_ASK_SAVE {
            get {
                return ResourceManager.GetString("MSG_PRJ_ASK_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder that will contain your new project..
        /// </summary>
        internal static string MSG_SELECT_FOLDER {
            get {
                return ResourceManager.GetString("MSG_SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message !.
        /// </summary>
        internal static string MSG_TITLE {
            get {
                return ResourceManager.GetString("MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file ?.
        /// </summary>
        internal static string MSG_WANTDELETE {
            get {
                return ResourceManager.GetString("MSG_WANTDELETE", resourceCulture);
            }
        }
    }
}
