//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectionStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReflectionStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the distant file after retreiving ?.
        /// </summary>
        internal static string MSG_DELETE_DISTANT_SNAP {
            get {
                return ResourceManager.GetString("MSG_DELETE_DISTANT_SNAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no database provider installed !.
        /// </summary>
        internal static string MSG_NO_DBPROVIDER {
            get {
                return ResourceManager.GetString("MSG_NO_DBPROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has some changes! Do you want to save it ?..
        /// </summary>
        internal static string MSG_PRJ_ASK_SAVE {
            get {
                return ResourceManager.GetString("MSG_PRJ_ASK_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project build canceled !.
        /// </summary>
        internal static string MSG_PROJECT_BUILD_CANCEL {
            get {
                return ResourceManager.GetString("MSG_PROJECT_BUILD_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project build error !.
        /// </summary>
        internal static string MSG_PROJECT_BUILD_ERROR {
            get {
                return ResourceManager.GetString("MSG_PROJECT_BUILD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project builded !.
        /// </summary>
        internal static string MSG_PROJECT_BUILD_OK {
            get {
                return ResourceManager.GetString("MSG_PROJECT_BUILD_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start building the project....
        /// </summary>
        internal static string MSG_PROJECT_START_BUILD {
            get {
                return ResourceManager.GetString("MSG_PROJECT_START_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder that will contain your new project..
        /// </summary>
        internal static string MSG_SELECT_FOLDER {
            get {
                return ResourceManager.GetString("MSG_SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snapshot file was successfully deleted !.
        /// </summary>
        internal static string MSG_SNAP_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SNAP_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snapshot file was successfully retreived !.
        /// </summary>
        internal static string MSG_SNAP_RETREIVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SNAP_RETREIVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message !.
        /// </summary>
        internal static string MSG_TITLE {
            get {
                return ResourceManager.GetString("MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection Studio.
        /// </summary>
        internal static string PROGRAMM_TITLE {
            get {
                return ResourceManager.GetString("PROGRAMM_TITLE", resourceCulture);
            }
        }
    }
}
